services:
  # The PHP Application Service
  php:
    build: . # Tells Docker to build an image from the Dockerfile in this directory
    volumes:
      - ./:/var/www/html # Mounts your project code into the container
    networks:
      - app-net

  # The Nginx Webserver Service
  nginx:
    image: nginx:1.27-alpine # Use a standard, lightweight Nginx image
    ports:
      - "8080:80" # Expose the container's port 80 on your machine's port 8080
    volumes:
      - ./:/var/www/html:ro # Mount code read-only
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro # Mount our Nginx config
    depends_on:
      - php # Nginx won't start until the PHP service is ready
    networks:
      - app-net

  # The PostgreSQL Database Service
  postgres:
    image: postgres:16-alpine # Use a standard PostgreSQL image
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: app_db
    volumes:
      - pg-data:/var/lib/postgresql/data # Persist database data on your machine
    networks:
      - app-net

networks:
  app-net: # The private network our services use to talk to each other

volumes:
  pg-data: # The named volume for our database
