name: Basic PHP Check

# Only run on main branch (not dev, to avoid annoying failures)
on:
    push:
        branches: ["main"]

jobs:
    check:
        runs-on: ubuntu-latest

        steps:
            # 1. Check out code
            - name: Checkout
              uses: actions/checkout@v4

            # 2. Setup PHP
            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: "8.3"

            # 3. Install dependencies
            - name: Install Composer dependencies
              run: composer install --no-interaction --no-dev --prefer-dist

            # 4. Check if PHP syntax is valid
            - name: Check PHP syntax
              run: find app resources routes -name "*.php" -exec php -l {} \;
